### ISSUE TITLE
Does not import dependencies after converting to require-from-string (missing file names)

### ISSUE THREAD

**Issue by b3ngineer** [KrazyCouponLady/gulp-aws-lambda-runner#1]
This issue will cause an error (example below) because the files aren't being named during compile.

**Error: Cannot find module './local.file'**
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (evalmachine.<anonymous>:1:76)
    at Module._compile (module.js:460:26)
    at requireFromString (/Users/name/git/some/node_modules/require-from-string/index.js:26:4)
    at DestroyableTransform.read [as _transform](/Users/name/git/some/node_modules/gulp-aws-lambda-runner/index.js:23:17)
    at DestroyableTransform.Transform._read (/Users/name/git/some/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (/Users/name/git/some//node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:160:12)

**Comment by b3ngineer** [comment]
Fixed in v1.0.1.
